### ISSUE TITLE
Feature request: Add lua API

### ISSUE THREAD

**Issue by Diaoul** [linrongbin16/gitlinker.nvim#213]
I prefer to have my mappings as lua calls than commands as it generally allows a much more finer grained control over what is happening.

Could you add such API?

**Comment by linrongbin16** [comment]
hi @Diaoul,

I will have a try

**Comment by Diaoul** [comment]
Thanks for the detailed and fast answer ⚡

I like your ideas, I would suggest to maybe abstract a bit more the internals so it can be more user friendly for the basic use cases.

In particular, I would suggest to not pass the `router` and have one function per router.
```lua
require("gitlinker").browse_link(opts)
require("gitlinker").blame_link(opts)
```

We could go even deeper with this and have one per router x action:
```lua
require("gitlinker").open_browse_link(opts)
require("gitlinker").copy_browse_link(opts)
require("gitlinker").open_blame_link(opts)
require("gitlinker").copy_blame_link(opts)
```

So in mappings one could do the following without having to wrap the call into another function:
```lua
-- browse
vim.keymap.set(
  {"n", 'v'},
  "<leader>gl",
  require("gitlinker").copy_browse_link,
  { silent = true, noremap = true, desc = "Copy git permlink to clipboard" }
)
```

No strong opinion here, I'm happy with what you suggest and I could probably understand how to achieve what I want by reading the types and docstrings but it's always nice to have an explicit function that matches exactly what you want to achieve.

**Comment by linrongbin16** [comment]
hi @Diaoul ,

PR #215 is merged into master branch, please pull and have a try.

Please notice that, finally the `link` behavior has a little change, because internally this plugins uses lua coroutine to avoid blocking, so the `link` API is actually running in async mode. So it doesn't has returned value.

If all you need is binding keys with pure lua function (instead of vim command `GitLink`), please refer to [Recommended Key Mappings](https://github.com/linrongbin16/gitlinker.nvim?tab=readme-ov-file#recommended-key-mappings)
